// Lip Sync Bingo call decks — real artist/song pairs, not generic filler.
// Each item is either a plain 'song' square (ARTIST / SONG) or a 'lipsync'
// square (LIP SYNC / ARTIST / SONG / MOOD) — the spec calls for roughly one
// lip-sync square per row when the deck supports it, so decks lean ~20%
// lipsync entries. `id` is the stable identity used for call/cover/win
// matching — never the display text, so retitling an item is always safe.
const slug = (artist, song) => `${artist}-${song}`.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
const song = (artist, title, genre, era, energy = 'high') =>
  ({ id: slug(artist, title), artist, song: title, type: 'song', genre, era, energy, lipSyncPotential: 8 });
const lip = (artist, title, genre, era, mood, energy = 'high') =>
  ({ id: slug(artist, title) + '-lip', artist, song: title, type: 'lipsync', genre, era, mood, energy, lipSyncPotential: 10 });

export const BINGO_DECKS = {
  'after-spot-starter': {
    name: 'After Spot Starter',
    description: 'Balanced HITMANS VIP starter deck for late-night private member play.',
    items: [
      song('Usher', 'Yeah!', 'R&B / Club', '2000s'),
      lip('Mary J. Blige', 'Family Affair', 'R&B', '2000s', 'Big auntie energy'),
      song('Outkast', 'Hey Ya!', 'Pop Rap', '2000s'),
      song('Drake', 'Nice For What', 'Rap', '2010s'),
      song('T-Pain', 'Buy U A Drank', 'R&B / Rap', '2000s'),
      lip('Aaliyah', 'Rock The Boat', 'R&B', '2000s', 'Smooth groove'),
      song('Missy Elliott', 'Work It', 'Hip Hop', '2000s'),
      song('Bruno Mars', 'Uptown Funk', 'Funk / Pop', '2010s'),
      lip('Rihanna', 'Work', 'Dancehall / Pop', '2010s', 'Island party energy'),
      song('Latto', 'Big Energy', 'Rap / Pop', '2020s'),
      song('Beyoncé', 'Crazy in Love', 'R&B', '2000s'),
      lip('Lil Wayne', 'A Milli', 'Rap', '2000s', 'Rap face-off'),
      song('Chris Brown', 'No Guidance', 'R&B', '2010s'),
      song('SZA', 'Kill Bill', 'R&B', '2020s'),
      lip('Cardi B', 'Up', 'Rap', '2020s', 'Boss energy'),
      song('Ciara', '1, 2 Step', 'R&B / Dance', '2000s'),
      song('Migos', 'Bad and Boujee', 'Trap', '2010s'),
      lip('Whitney Houston', 'I Wanna Dance With Somebody', 'Pop', '1980s', 'Full crowd singalong'),
      song('TLC', 'No Scrubs', 'R&B', '1990s'),
      song('Future', 'Mask Off', 'Trap', '2010s'),
      lip('Beyoncé', 'Cuff It', 'R&B / Dance', '2020s', 'Dance groove'),
      song('Nicki Minaj', 'Super Bass', 'Rap', '2010s'),
      song('Glorilla', 'Tomorrow 2', 'Rap', '2020s'),
      lip('Luther Vandross', 'Never Too Much', 'Soul', '1980s', 'Smooth performer'),
      song('Kodak Black', 'No Flockin', 'Rap', '2010s'),
      song('Rick Ross', 'Aston Martin Music', 'Rap', '2010s'),
    ],
  },
  'famu-fsu-tcc': {
    name: 'FAMU / FSU / TCC',
    description: 'Tallahassee college-night crowd — HBCU chants, step shows, dorm party classics.',
    items: [
      song('T-Pain', 'Bartender', 'R&B / Rap', '2000s'),
      lip('Plies', 'Bust It Baby Pt. 2', 'Southern Rap', '2000s', 'Southern throwback'),
      song('Drake', 'Nice For What', 'Rap', '2010s'),
      lip('Glorilla', 'Tomorrow 2', 'Rap', '2020s', 'Crowd rap'),
      song('Sexyy Red', 'SkeeYee', 'Rap', '2020s'),
      lip('Lil Wayne', 'Lollipop', 'Rap', '2000s', '2000s club'),
      song('Beyoncé', 'Cuff It', 'R&B / Dance', '2020s'),
      lip('Chris Brown', 'No Guidance', 'R&B', '2010s', 'Smooth performer'),
      song('Migos', 'Bad and Boujee', 'Trap', '2010s'),
      song('Travis Scott', 'SICKO MODE', 'Trap', '2010s'),
      lip('City Girls', 'Act Up', 'Rap', '2010s', 'Ladies anthem'),
      song('Future', 'Mask Off', 'Trap', '2010s'),
      song('Moneybagg Yo', 'Wockesha', 'Trap', '2020s'),
      lip('Nicki Minaj', 'Super Bass', 'Rap', '2010s', 'Sing every word'),
      song('Lil Baby', 'Drip Too Hard', 'Trap', '2010s'),
      song('21 Savage', 'A Lot', 'Trap', '2010s'),
      lip('Trina', 'Pull Over', 'Southern Rap', '2000s', 'Bold energy'),
      song('Cardi B', 'Up', 'Rap', '2020s'),
      song('OutKast', 'So Fresh, So Clean', 'Pop Rap', '2000s'),
      lip('Usher', 'Yeah!', 'R&B / Club', '2000s', 'High energy'),
      song('Kodak Black', 'No Flockin', 'Rap', '2010s'),
      song('Rick Ross', 'Aston Martin Music', 'Rap', '2010s'),
      lip('Ludacris', 'Move Bitch', 'Rap', '2000s', 'Parking lot anthem'),
      song('Gucci Mane', 'Wasted', 'Trap', '2010s'),
      song('2 Chainz', 'No Lie', 'Rap', '2010s'),
      lip('Young Dolph', 'Get Paid', 'Trap', '2010s', 'Boss walk'),
    ],
  },
  'tally-after-dark': {
    name: 'Tally After Dark',
    description: '3AM energy — southern bounce, ladies night, DJ replay classics.',
    items: [
      lip('T-Pain', "I'm Sprung", 'R&B / Rap', '2000s', 'Tally classic'),
      song('Trina', 'Pull Over', 'Southern Rap', '2000s'),
      lip('Lil Jon', 'Get Low', 'Crunk', '2000s', 'Crowd wild'),
      song('Ying Yang Twins', 'Salt Shaker', 'Crunk', '2000s'),
      lip('Future', 'March Madness', 'Trap', '2010s', 'Late night'),
      song('Kodak Black', 'No Flockin', 'Rap', '2010s'),
      lip('Rick Ross', 'Aston Martin Music', 'Rap', '2010s', 'Boss vibe'),
      song('OutKast', 'So Fresh, So Clean', 'Pop Rap', '2000s'),
      song('Trick Daddy', "I'm a Thug", 'Southern Rap', '2000s'),
      lip('City Girls', 'Twerk', 'Rap', '2010s', 'Ladies night'),
      song('Flo Milli', 'Beef FloMix', 'Rap', '2020s'),
      song('Young Jeezy', 'Soul Survivor', 'Trap', '2000s'),
      lip('Webbie', 'Independent', 'Southern Rap', '2000s', 'Southern bounce'),
      song('Boosie Badazz', 'Wipe Me Down', 'Southern Rap', '2000s'),
      song('Pastor Troy', 'Vice Versa', 'Crunk', '2000s'),
      lip('Migos', 'Bad and Boujee', 'Trap', '2010s', 'Bass drop'),
      song('Gucci Mane', 'Wasted', 'Trap', '2010s'),
      song('2 Chainz', 'No Lie', 'Rap', '2010s'),
      lip('Ludacris', 'Move Bitch', 'Rap', '2000s', 'VIP line song'),
      song('Young Dolph', 'Get Paid', 'Trap', '2010s'),
      song('Moneybagg Yo', 'Wockesha', 'Trap', '2020s'),
      lip('Sexyy Red', 'SkeeYee', 'Rap', '2020s', 'Party chant'),
      song('Latto', 'Big Energy', 'Rap / Pop', '2020s'),
      song('Ying Yang Twins', 'Wait (The Whisper Song)', 'Crunk', '2000s'),
    ],
  },
  'rnb-slow-jams': {
    name: 'R&B Slow Jams',
    description: 'Closing-time R&B — the last-hour, lights-up, couples-up deck.',
    items: [
      lip('Luther Vandross', 'Never Too Much', 'Soul', '1980s', 'Smooth performer'),
      song('Boyz II Men', "I'll Make Love to You", 'R&B', '1990s'),
      lip('Aaliyah', 'Rock The Boat', 'R&B', '2000s', 'Smooth groove'),
      song('Jodeci', 'Freek\'n You', 'R&B', '1990s'),
      lip('Mary J. Blige', 'Family Affair', 'R&B', '2000s', 'Big auntie energy'),
      song('Usher', 'Confessions Part II', 'R&B', '2000s'),
      lip('Ginuwine', 'So Anxious', 'R&B', '1990s', 'Slow groove'),
      song('SZA', 'Snooze', 'R&B', '2020s'),
      lip('Jill Scott', 'A Long Walk', 'Neo Soul', '2000s', 'Soulful'),
      song('Musiq Soulchild', 'Just Friends', 'Neo Soul', '2000s'),
      lip('Chris Brown', 'No Guidance', 'R&B', '2010s', 'Smooth performer'),
      song('H.E.R.', 'Best Part', 'R&B', '2010s'),
      lip('Whitney Houston', 'I Will Always Love You', 'Pop / Soul', '1990s', 'Full crowd singalong'),
      song('Toni Braxton', 'Un-Break My Heart', 'R&B', '1990s'),
      lip('Brandy', 'Have You Ever?', 'R&B', '1990s', 'Emotional ballad'),
      song('Monica', 'Angel of Mine', 'R&B', '1990s'),
      lip('Trey Songz', 'Can\'t Help But Wait', 'R&B', '2000s', 'Slow dance'),
      song('Keith Sweat', 'Nobody', 'R&B', '1990s'),
      lip('Beyoncé', 'Dangerously in Love', 'R&B', '2000s', 'Star performer'),
      song('Ne-Yo', 'So Sick', 'R&B', '2000s'),
      lip('Mariah Carey', 'We Belong Together', 'R&B / Pop', '2000s', 'Big vocal moment'),
      song('Anita Baker', 'Sweet Love', 'Soul', '1980s'),
      lip('Jagged Edge', 'Let\'s Get Married', 'R&B', '1990s', 'Crowd singalong'),
      song('Silk', 'Freak Me', 'R&B', '1990s'),
      song('Case', 'Happily Ever After', 'R&B', '1990s'),
    ],
  },
};
export const DEFAULT_DECK_ID = 'after-spot-starter';
export const deckList = () => Object.entries(BINGO_DECKS).map(([id, d]) => ({ id, name: d.name, description: d.description, count: d.items.length }));
export const deckById = (id) => BINGO_DECKS[id] || BINGO_DECKS[DEFAULT_DECK_ID];
