// Lip Sync Bingo call decks — real artist/song pairs, not generic filler.
// Each item is either a plain 'song' square (ARTIST / SONG) or a 'lipsync'
// square (LIP SYNC / ARTIST / SONG / MOOD) — the spec calls for roughly one
// lip-sync square per row when the deck supports it, so decks lean ~20%
// lipsync entries. `id` is the stable identity used for call/cover/win
// matching — never the display text, so retitling an item is always safe.
import { DECK_VIDEO_IDS } from './deck-videos.mjs';

const slug = (artist, song) => `${artist}-${song}`.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
const song = (artist, title, genre, era, energy = 'high') =>
  ({ id: slug(artist, title), artist, song: title, type: 'song', genre, era, energy, lipSyncPotential: 8 });
const lip = (artist, title, genre, era, mood, energy = 'high') =>
  ({ id: slug(artist, title) + '-lip', artist, song: title, type: 'lipsync', genre, era, mood, energy, lipSyncPotential: 10 });

export const BINGO_DECKS = {
  'after-spot-starter': {
    name: 'After Spot Starter',
    description: 'Balanced HITMANS VIP starter deck for late-night private member play.',
    items: [
      song('Usher', 'Yeah!', 'R&B / Club', '2000s'),
      lip('Mary J. Blige', 'Family Affair', 'R&B', '2000s', 'Big auntie energy'),
      song('Outkast', 'Hey Ya!', 'Pop Rap', '2000s'),
      song('Drake', 'Nice For What', 'Rap', '2010s'),
      song('T-Pain', 'Buy U A Drank', 'R&B / Rap', '2000s'),
      lip('Aaliyah', 'Rock The Boat', 'R&B', '2000s', 'Smooth groove'),
      song('Missy Elliott', 'Work It', 'Hip Hop', '2000s'),
      song('Bruno Mars', 'Uptown Funk', 'Funk / Pop', '2010s'),
      lip('Rihanna', 'Work', 'Dancehall / Pop', '2010s', 'Island party energy'),
      song('Latto', 'Big Energy', 'Rap / Pop', '2020s'),
      song('Beyoncé', 'Crazy in Love', 'R&B', '2000s'),
      lip('Lil Wayne', 'A Milli', 'Rap', '2000s', 'Rap face-off'),
      song('Chris Brown', 'No Guidance', 'R&B', '2010s'),
      song('SZA', 'Kill Bill', 'R&B', '2020s'),
      lip('Cardi B', 'Up', 'Rap', '2020s', 'Boss energy'),
      song('Ciara', '1, 2 Step', 'R&B / Dance', '2000s'),
      song('Migos', 'Bad and Boujee', 'Trap', '2010s'),
      lip('Whitney Houston', 'I Wanna Dance With Somebody', 'Pop', '1980s', 'Full crowd singalong'),
      song('TLC', 'No Scrubs', 'R&B', '1990s'),
      song('Future', 'Mask Off', 'Trap', '2010s'),
      lip('Beyoncé', 'Cuff It', 'R&B / Dance', '2020s', 'Dance groove'),
      song('Nicki Minaj', 'Super Bass', 'Rap', '2010s'),
      song('Glorilla', 'Tomorrow 2', 'Rap', '2020s'),
      lip('Luther Vandross', 'Never Too Much', 'Soul', '1980s', 'Smooth performer'),
      song('Kodak Black', 'No Flockin', 'Rap', '2010s'),
      song('Rick Ross', 'Aston Martin Music', 'Rap', '2010s'),
    ],
  },
  'famu-fsu-tcc': {
    name: 'FAMU / FSU / TCC',
    description: 'Tallahassee college-night crowd — HBCU chants, step shows, dorm party classics.',
    items: [
      song('T-Pain', 'Bartender', 'R&B / Rap', '2000s'),
      lip('Plies', 'Bust It Baby Pt. 2', 'Southern Rap', '2000s', 'Southern throwback'),
      song('Drake', 'Nice For What', 'Rap', '2010s'),
      lip('Glorilla', 'Tomorrow 2', 'Rap', '2020s', 'Crowd rap'),
      song('Sexyy Red', 'SkeeYee', 'Rap', '2020s'),
      lip('Lil Wayne', 'Lollipop', 'Rap', '2000s', '2000s club'),
      song('Beyoncé', 'Cuff It', 'R&B / Dance', '2020s'),
      lip('Chris Brown', 'No Guidance', 'R&B', '2010s', 'Smooth performer'),
      song('Migos', 'Bad and Boujee', 'Trap', '2010s'),
      song('Travis Scott', 'SICKO MODE', 'Trap', '2010s'),
      lip('City Girls', 'Act Up', 'Rap', '2010s', 'Ladies anthem'),
      song('Future', 'Mask Off', 'Trap', '2010s'),
      song('Moneybagg Yo', 'Wockesha', 'Trap', '2020s'),
      lip('Nicki Minaj', 'Super Bass', 'Rap', '2010s', 'Sing every word'),
      song('Lil Baby', 'Drip Too Hard', 'Trap', '2010s'),
      song('21 Savage', 'A Lot', 'Trap', '2010s'),
      lip('Trina', 'Pull Over', 'Southern Rap', '2000s', 'Bold energy'),
      song('Cardi B', 'Up', 'Rap', '2020s'),
      song('OutKast', 'So Fresh, So Clean', 'Pop Rap', '2000s'),
      lip('Usher', 'Yeah!', 'R&B / Club', '2000s', 'High energy'),
      song('Kodak Black', 'No Flockin', 'Rap', '2010s'),
      song('Rick Ross', 'Aston Martin Music', 'Rap', '2010s'),
      lip('Ludacris', 'Move Bitch', 'Rap', '2000s', 'Parking lot anthem'),
      song('Gucci Mane', 'Wasted', 'Trap', '2010s'),
      song('2 Chainz', 'No Lie', 'Rap', '2010s'),
      lip('Young Dolph', 'Get Paid', 'Trap', '2010s', 'Boss walk'),
    ],
  },
  'tally-after-dark': {
    name: 'Tally After Dark',
    description: '3AM energy — southern bounce, ladies night, DJ replay classics.',
    items: [
      lip('T-Pain', "I'm Sprung", 'R&B / Rap', '2000s', 'Tally classic'),
      song('Trina', 'Pull Over', 'Southern Rap', '2000s'),
      lip('Lil Jon', 'Get Low', 'Crunk', '2000s', 'Crowd wild'),
      song('Ying Yang Twins', 'Salt Shaker', 'Crunk', '2000s'),
      lip('Future', 'March Madness', 'Trap', '2010s', 'Late night'),
      song('Kodak Black', 'No Flockin', 'Rap', '2010s'),
      lip('Rick Ross', 'Aston Martin Music', 'Rap', '2010s', 'Boss vibe'),
      song('OutKast', 'So Fresh, So Clean', 'Pop Rap', '2000s'),
      song('Trick Daddy', "I'm a Thug", 'Southern Rap', '2000s'),
      lip('City Girls', 'Twerk', 'Rap', '2010s', 'Ladies night'),
      song('Flo Milli', 'Beef FloMix', 'Rap', '2020s'),
      song('Young Jeezy', 'Soul Survivor', 'Trap', '2000s'),
      lip('Webbie', 'Independent', 'Southern Rap', '2000s', 'Southern bounce'),
      song('Boosie Badazz', 'Wipe Me Down', 'Southern Rap', '2000s'),
      song('Pastor Troy', 'Vice Versa', 'Crunk', '2000s'),
      lip('Migos', 'Bad and Boujee', 'Trap', '2010s', 'Bass drop'),
      song('Gucci Mane', 'Wasted', 'Trap', '2010s'),
      song('2 Chainz', 'No Lie', 'Rap', '2010s'),
      lip('Ludacris', 'Move Bitch', 'Rap', '2000s', 'VIP line song'),
      song('Young Dolph', 'Get Paid', 'Trap', '2010s'),
      song('Moneybagg Yo', 'Wockesha', 'Trap', '2020s'),
      lip('Sexyy Red', 'SkeeYee', 'Rap', '2020s', 'Party chant'),
      song('Latto', 'Big Energy', 'Rap / Pop', '2020s'),
      song('Ying Yang Twins', 'Wait (The Whisper Song)', 'Crunk', '2000s'),
    ],
  },
  'rnb-slow-jams': {
    name: 'R&B Slow Jams',
    description: 'Closing-time R&B — the last-hour, lights-up, couples-up deck.',
    items: [
      lip('Luther Vandross', 'Never Too Much', 'Soul', '1980s', 'Smooth performer'),
      song('Boyz II Men', "I'll Make Love to You", 'R&B', '1990s'),
      lip('Aaliyah', 'Rock The Boat', 'R&B', '2000s', 'Smooth groove'),
      song('Jodeci', 'Freek\'n You', 'R&B', '1990s'),
      lip('Mary J. Blige', 'Family Affair', 'R&B', '2000s', 'Big auntie energy'),
      song('Usher', 'Confessions Part II', 'R&B', '2000s'),
      lip('Ginuwine', 'So Anxious', 'R&B', '1990s', 'Slow groove'),
      song('SZA', 'Snooze', 'R&B', '2020s'),
      lip('Jill Scott', 'A Long Walk', 'Neo Soul', '2000s', 'Soulful'),
      song('Musiq Soulchild', 'Just Friends', 'Neo Soul', '2000s'),
      lip('Chris Brown', 'No Guidance', 'R&B', '2010s', 'Smooth performer'),
      song('H.E.R.', 'Best Part', 'R&B', '2010s'),
      lip('Whitney Houston', 'I Will Always Love You', 'Pop / Soul', '1990s', 'Full crowd singalong'),
      song('Toni Braxton', 'Un-Break My Heart', 'R&B', '1990s'),
      lip('Brandy', 'Have You Ever?', 'R&B', '1990s', 'Emotional ballad'),
      song('Monica', 'Angel of Mine', 'R&B', '1990s'),
      lip('Trey Songz', 'Can\'t Help But Wait', 'R&B', '2000s', 'Slow dance'),
      song('Keith Sweat', 'Nobody', 'R&B', '1990s'),
      lip('Beyoncé', 'Dangerously in Love', 'R&B', '2000s', 'Star performer'),
      song('Ne-Yo', 'So Sick', 'R&B', '2000s'),
      lip('Mariah Carey', 'We Belong Together', 'R&B / Pop', '2000s', 'Big vocal moment'),
      song('Anita Baker', 'Sweet Love', 'Soul', '1980s'),
      lip('Jagged Edge', 'Let\'s Get Married', 'R&B', '1990s', 'Crowd singalong'),
      song('Silk', 'Freak Me', 'R&B', '1990s'),
      song('Case', 'Happily Ever After', 'R&B', '1990s'),
    ],
  },
  // ── Genre decks ──────────────────────────────────────────────────────
  // The five genre chips printed on lsb_sheet_03, as real decks. Every deck
  // stays inside one lane on purpose: the host's YouTube queue is fed straight
  // from whatever gets called, so a deck that wanders across genres makes the
  // room's music wander with it. One deck, one flow.
  'nineties-hiphop-rnb': {
    name: '90s Hip-Hop & R&B',
    description: 'The 90s block — boom bap and quiet storm, nothing after 1999.',
    items: [
      lip('The Notorious B.I.G.', 'Juicy', 'Hip Hop', '1990s', 'Rap face-off'),
      song('2Pac', 'California Love', 'Hip Hop', '1990s'),
      song('Dr. Dre', 'Nuthin\' but a "G" Thang', 'G-Funk', '1990s'),
      lip('TLC', 'No Scrubs', 'R&B', '1990s', 'Group attitude'),
      song('SWV', 'Weak', 'R&B', '1990s'),
      lip('Missy Elliott', 'The Rain (Supa Dupa Fly)', 'Hip Hop', '1990s', 'Full character piece'),
      song('A Tribe Called Quest', 'Can I Kick It?', 'Hip Hop', '1990s'),
      lip('Lauryn Hill', 'Doo Wop (That Thing)', 'Hip Hop / Soul', '1990s', 'Preacher energy'),
      song('Nas', 'If I Ruled the World', 'Hip Hop', '1990s'),
      song('Wu-Tang Clan', 'C.R.E.A.M.', 'Hip Hop', '1990s'),
      lip('Bell Biv DeVoe', 'Poison', 'New Jack Swing', '1990s', 'Full choreography'),
      song('Blackstreet', 'No Diggity', 'R&B', '1990s'),
      lip('Aaliyah', 'Are You That Somebody?', 'R&B', '1990s', 'Smooth groove'),
      song('Ginuwine', 'Pony', 'R&B', '1990s'),
      song('Mary J. Blige', 'Real Love', 'R&B', '1990s'),
      lip('Salt-N-Pepa', 'Shoop', 'Hip Hop', '1990s', 'Group attitude'),
      song('Warren G', 'Regulate', 'G-Funk', '1990s'),
      lip('Montell Jordan', 'This Is How We Do It', 'R&B', '1990s', 'Crowd singalong'),
      song('Total', 'Can\'t You See', 'R&B', '1990s'),
      song('Jodeci', 'Come & Talk to Me', 'R&B', '1990s'),
      lip('Busta Rhymes', 'Woo Hah!! Got You All in Check', 'Hip Hop', '1990s', 'Wild energy'),
      song('Method Man', 'All I Need', 'Hip Hop', '1990s'),
      song('Brandy', 'I Wanna Be Down', 'R&B', '1990s'),
      lip('Bone Thugs-N-Harmony', 'Tha Crossroads', 'Hip Hop', '1990s', 'Fast harmony'),
      song('Xscape', 'Just Kickin\' It', 'R&B', '1990s'),
      song('Naughty by Nature', 'Hip Hop Hooray', 'Hip Hop', '1990s'),
    ],
  },
  'edm-house': {
    name: 'EDM / House',
    description: 'Four-on-the-floor — the peak-hour dance block.',
    items: [
      lip('Daft Punk', 'One More Time', 'House', '2000s', 'Robot energy'),
      song('Calvin Harris', 'Feel So Close', 'EDM', '2010s'),
      song('Swedish House Mafia', 'Don\'t You Worry Child', 'EDM', '2010s'),
      lip('Robin S.', 'Show Me Love', 'House', '1990s', 'Diva vocal'),
      song('Avicii', 'Levels', 'EDM', '2010s'),
      lip('Crystal Waters', 'Gypsy Woman', 'House', '1990s', 'Diva vocal'),
      song('Disclosure', 'Latch', 'House', '2010s'),
      song('Fisher', 'Losing It', 'Tech House', '2010s'),
      lip('Beyoncé', 'BREAK MY SOUL', 'House', '2020s', 'Star performer'),
      song('Drake', 'Massive', 'House', '2020s'),
      lip('Frankie Knuckles', 'Your Love', 'Chicago House', '1980s', 'Deep groove'),
      song('Kaytranada', '10%', 'House', '2020s'),
      song('Duke Dumont', 'Need U (100%)', 'House', '2010s'),
      lip('Charli XCX', '360', 'Hyperpop / Dance', '2020s', 'Full character piece'),
      song('Fred again..', 'Turn On The Lights again..', 'EDM', '2020s'),
      lip('Whitney Houston', 'It\'s Not Right but It\'s Okay (Thunderpuss)', 'House', '1990s', 'Big vocal moment'),
      song('Major Lazer', 'Lean On', 'Moombahton', '2010s'),
      song('Zedd', 'Clarity', 'EDM', '2010s'),
      lip('Sylvester', 'You Make Me Feel (Mighty Real)', 'Disco / House', '1970s', 'Full diva'),
      song('Deee-Lite', 'Groove Is in the Heart', 'Dance', '1990s'),
      lip('Cascada', 'Everytime We Touch', 'Eurodance', '2000s', 'Crowd singalong'),
      song('David Guetta', 'Titanium', 'EDM', '2010s'),
      song('Peggy Gou', '(It Goes Like) Nanana', 'House', '2020s'),
      lip('Technotronic', 'Pump Up the Jam', 'House', '1980s', 'Full choreography'),
      song('Alok', 'Hear Me Now', 'EDM', '2010s'),
      song('Chris Lake', 'Turn Off The Lights', 'Tech House', '2020s'),
    ],
  },
  'afrobeats': {
    name: 'Afrobeats',
    description: 'Afrobeats and amapiano — the late-set international block.',
    items: [
      lip('Burna Boy', 'Last Last', 'Afrobeats', '2020s', 'Heartbreak swagger'),
      song('Wizkid', 'Essence', 'Afrobeats', '2020s'),
      song('Davido', 'Fall', 'Afrobeats', '2010s'),
      lip('Tems', 'Free Mind', 'Alté / R&B', '2020s', 'Soulful'),
      song('Rema', 'Calm Down', 'Afrobeats', '2020s'),
      lip('Ckay', 'Love Nwantiti', 'Afrobeats', '2020s', 'Smooth groove'),
      song('Asake', 'Lonely At The Top', 'Afrobeats', '2020s'),
      song('Fireboy DML', 'Peru', 'Afrobeats', '2020s'),
      lip('Yemi Alade', 'Johnny', 'Afrobeats', '2010s', 'Full character piece'),
      song('Ayra Starr', 'Rush', 'Afrobeats', '2020s'),
      lip('Fela Kuti', 'Water No Get Enemy', 'Afrobeat', '1970s', 'Bandleader energy'),
      song('Mr Eazi', 'Leg Over', 'Afrobeats', '2010s'),
      song('Tiwa Savage', 'Koroba', 'Afrobeats', '2020s'),
      lip('Kabza De Small', 'Sponono', 'Amapiano', '2020s', 'Deep groove'),
      song('Uncle Waffles', 'Tanzania', 'Amapiano', '2020s'),
      lip('Master KG', 'Jerusalema', 'Amapiano', '2010s', 'Full choreography'),
      song('Omah Lay', 'Soso', 'Afrobeats', '2020s'),
      song('Joeboy', 'Baby', 'Afrobeats', '2010s'),
      lip('Angelique Kidjo', 'Agolo', 'Afropop', '1990s', 'Full diva'),
      song('P-Square', 'Personally', 'Afrobeats', '2010s'),
      lip('Sauti Sol', 'Suzanna', 'Afropop', '2010s', 'Group attitude'),
      song('Libianca', 'People', 'Afrobeats', '2020s'),
      song('Black Sherif', 'Kwaku the Traveller', 'Afrobeats', '2020s'),
      lip('Shatta Wale', 'Already', 'Dancehall / Afrobeats', '2020s', 'Island party energy'),
      song('Kizz Daniel', 'Buga', 'Afrobeats', '2020s'),
      song('Adekunle Gold', 'Party No Dey Stop', 'Afrobeats', '2020s'),
    ],
  },
  'country': {
    name: 'Country',
    description: 'Country night — line-dance floor fillers and singalong ballads.',
    items: [
      lip('Dolly Parton', 'Jolene', 'Country', '1970s', 'Story ballad'),
      song('Johnny Cash', 'Ring of Fire', 'Country', '1960s'),
      song('Shania Twain', 'Man! I Feel Like a Woman!', 'Country Pop', '1990s'),
      lip('Garth Brooks', 'Friends in Low Places', 'Country', '1990s', 'Crowd singalong'),
      song('Luke Combs', 'Beautiful Crazy', 'Country', '2010s'),
      lip('Beyoncé', 'TEXAS HOLD \'EM', 'Country', '2020s', 'Star performer'),
      song('Morgan Wallen', 'Last Night', 'Country', '2020s'),
      song('Kacey Musgraves', 'Follow Your Arrow', 'Country', '2010s'),
      lip('Carrie Underwood', 'Before He Cheats', 'Country', '2000s', 'Full attitude'),
      song('Chris Stapleton', 'Tennessee Whiskey', 'Country Soul', '2010s'),
      lip('Willie Nelson', 'On the Road Again', 'Country', '1980s', 'Easy swagger'),
      song('Zach Bryan', 'Something in the Orange', 'Country', '2020s'),
      song('Tim McGraw', 'Live Like You Were Dying', 'Country', '2000s'),
      lip('Reba McEntire', 'Fancy', 'Country', '1990s', 'Story ballad'),
      song('Alan Jackson', 'Chattahoochee', 'Country', '1990s'),
      lip('Darius Rucker', 'Wagon Wheel', 'Country', '2010s', 'Crowd singalong'),
      song('Miranda Lambert', 'Gunpowder & Lead', 'Country', '2000s'),
      song('Brooks & Dunn', 'Boot Scootin\' Boogie', 'Country', '1990s'),
      lip('Patsy Cline', 'Crazy', 'Country', '1960s', 'Emotional ballad'),
      song('Kenny Chesney', 'No Shoes, No Shirt, No Problems', 'Country', '2000s'),
      lip('The Chicks', 'Goodbye Earl', 'Country', '1990s', 'Full character piece'),
      song('Jason Aldean', 'Dirt Road Anthem', 'Country Rap', '2010s'),
      song('Lainey Wilson', 'Things a Man Oughta Know', 'Country', '2020s'),
      lip('Cowboy Troy', 'I Play Chicken with the Train', 'Country Rap', '2000s', 'Wild energy'),
      song('Old Dominion', 'One Man Band', 'Country', '2010s'),
      song('Sam Hunt', 'Body Like a Back Road', 'Country Pop', '2010s'),
    ],
  },
  'ladies-in-hip-hop': {
    name: 'Ladies In Hip Hop',
    description: 'Women in rap, front to back — the loudest deck in the room.',
    items: [
      lip('Missy Elliott', 'Get Ur Freak On', 'Hip Hop', '2000s', 'Full character piece'),
      song('Nicki Minaj', 'Super Bass', 'Rap', '2010s'),
      song('Cardi B', 'Bodak Yellow', 'Rap', '2010s'),
      lip('Lil\' Kim', 'Crush On You', 'Hip Hop', '1990s', 'Full attitude'),
      song('Megan Thee Stallion', 'Savage', 'Rap', '2020s'),
      lip('Foxy Brown', 'I\'ll Be Good', 'Hip Hop', '1990s', 'Full attitude'),
      song('Doja Cat', 'Say So', 'Pop Rap', '2020s'),
      song('GloRilla', 'Tomorrow 2', 'Rap', '2020s'),
      lip('Queen Latifah', 'U.N.I.T.Y.', 'Hip Hop', '1990s', 'Preacher energy'),
      song('Latto', 'Big Energy', 'Rap / Pop', '2020s'),
      lip('MC Lyte', 'Ruffneck', 'Hip Hop', '1990s', 'Rap face-off'),
      song('Eve', 'Let Me Blow Ya Mind', 'Hip Hop', '2000s'),
      song('Trina', 'Da Baddest B****', 'Rap', '2000s'),
      lip('Da Brat', 'Funkdafied', 'Hip Hop', '1990s', 'Easy swagger'),
      song('Rapsody', 'Power', 'Hip Hop', '2010s'),
      lip('Salt-N-Pepa', 'Push It', 'Hip Hop', '1980s', 'Full choreography'),
      song('City Girls', 'Act Up', 'Rap', '2010s'),
      song('Ice Spice', 'Munch (Feelin\' U)', 'Drill', '2020s'),
      lip('Left Eye', 'Waterfalls (verse)', 'Hip Hop', '1990s', 'Fast verse'),
      song('Remy Ma', 'All the Way Up', 'Rap', '2010s'),
      lip('Sexyy Red', 'SkeeYee', 'Rap', '2020s', 'Wild energy'),
      song('Flo Milli', 'Beef FloMix', 'Rap', '2020s'),
      song('Saweetie', 'My Type', 'Rap', '2010s'),
      lip('Lauryn Hill', 'Lost Ones', 'Hip Hop', '1990s', 'Rap face-off'),
      song('JT', 'Okay', 'Rap', '2020s'),
      song('Rico Nasty', 'Smack a B****', 'Rap', '2010s'),
    ],
  },

  // ── Night themes ─────────────────────────────────────────────────────
  // A themed night is not a playlist with a label on it — the deck IS the
  // night. Everything called comes from here, so the room's whole hour follows
  // whichever one the host picked. Each of these has to stand on its own for a
  // full three rounds, which is why none is shorter than a card and a half.
  'ladies-night': {
    name: 'Ladies Night',
    description: 'Ladies night, front to back — the floor-filling women of R&B, rap and pop.',
    items: [
      lip('Beyoncé', 'Single Ladies (Put a Ring on It)', 'Pop / R&B', '2000s', 'Whole floor knows the dance'),
      song('Destiny’s Child', 'Say My Name', 'R&B', '1990s'),
      song('Rihanna', 'Pon de Replay', 'Dancehall / Pop', '2000s'),
      lip('Whitney Houston', 'I’m Every Woman', 'Pop / Soul', '1990s', 'Grown and glorious'),
      song('SZA', 'Good Days', 'R&B', '2020s'),
      song('Ariana Grande', '7 rings', 'Pop', '2010s'),
      lip('Missy Elliott', 'Get Ur Freak On', 'Hip Hop', '2000s', 'Nobody can keep up'),
      song('Megan Thee Stallion', 'Body', 'Rap', '2020s'),
      song('Doja Cat', 'Say So', 'Pop / R&B', '2020s'),
      lip('TLC', 'Waterfalls', 'R&B', '1990s', 'Three-part group moment'),
      song('Alicia Keys', 'No One', 'R&B / Soul', '2000s'),
      song('Jazmine Sullivan', 'Bust Your Windows', 'R&B', '2000s'),
      lip('Mary J. Blige', 'Real Love', 'R&B', '1990s', 'Queen of hip-hop soul'),
      song('Chlöe', 'Have Mercy', 'R&B', '2020s'),
      song('Normani', 'Motivation', 'Pop / R&B', '2010s'),
      lip('Aretha Franklin', 'Respect', 'Soul', '1960s', 'Church-loud, hands up'),
      song('Kelis', 'Milkshake', 'R&B / Dance', '2000s'),
      song('Ashanti', 'Foolish', 'R&B', '2000s'),
      lip('Tina Turner', 'Proud Mary', 'Rock / Soul', '1970s', 'Slow start, then everything'),
      song('Victoria Monét', 'On My Mama', 'R&B', '2020s'),
      song('Summer Walker', 'Girls Need Love', 'R&B', '2010s'),
      lip('Lauryn Hill', 'Doo Wop (That Thing)', 'Hip Hop / Soul', '1990s', 'Every word, no help'),
      song('Brandy', 'The Boy Is Mine', 'R&B', '1990s'),
      song('Ice Spice', 'Munch (Feelin’ U)', 'Rap', '2020s'),
      song('En Vogue', 'My Lovin’ (You’re Never Gonna Get It)', 'R&B', '1990s'),
      song('Sade', 'No Ordinary Love', 'Soul', '1990s', 'mid'),
    ],
  },
  'tallahassees-finest': {
    name: 'Tallahassee’s Finest',
    description: 'Home team — Tallahassee and North Florida artists, and the records this city claims.',
    items: [
      lip('T-Pain', 'I’m Sprung', 'R&B / Rap', '2000s', 'Tallahassee’s own — sing it right'),
      song('T-Pain', 'Bartender', 'R&B / Rap', '2000s'),
      song('Tay Dizm', 'Beam Me Up', 'Rap', '2000s'),
      lip('T-Pain', 'Can’t Believe It', 'R&B / Rap', '2000s', 'Auto-tune face-off'),
      song('Trick Daddy', 'Let’s Go', 'Rap', '2000s'),
      song('Rick Ross', 'Hustlin’', 'Rap', '2000s'),
      lip('Trina', 'Pull Over', 'Rap', '2000s', 'Florida ladies stand up'),
      song('Plies', 'Shawty', 'Rap', '2000s'),
      song('Kodak Black', 'Super Gremlin', 'Rap', '2020s'),
      lip('Flo Rida', 'Low', 'Rap / Club', '2000s', 'Apple bottom jeans — everybody'),
      song('DJ Khaled', 'All I Do Is Win', 'Rap', '2010s'),
      song('Ace Hood', 'Bugatti', 'Rap', '2010s'),
      lip('JT Money', 'Who Dat', 'Rap', '1990s', 'Old Florida, full throat'),
      song('Rick Ross', 'B.M.F. (Blowin’ Money Fast)', 'Rap', '2010s'),
      song('Kodak Black', 'Tunnel Vision', 'Rap', '2010s'),
      lip('Pitbull', 'Culo', 'Rap / Latin', '2000s', 'Miami-to-Tally energy'),
      song('Plies', 'Bust It Baby', 'Rap / R&B', '2000s'),
      song('Trick Daddy', 'I’m a Thug', 'Rap', '2000s'),
      lip('T-Pain', 'Buy U A Drank', 'R&B / Rap', '2000s', 'The one they came for'),
      song('Denzel Curry', 'Ultimate', 'Rap', '2010s'),
      song('Trina', 'Here We Go', 'Rap', '2000s'),
      song('Flo Rida', 'Good Feeling', 'Club / Pop', '2010s'),
      lip('Betty Wright', 'Clean Up Woman', 'Soul', '1970s', 'Grown folks approve'),
      song('Rick Ross', 'Diced Pineapples', 'Rap / R&B', '2010s', 'mid'),
      song('Ace Hood', 'Hustle Hard', 'Rap', '2010s'),
      song('Kodak Black', 'ZEZE', 'Rap', '2010s'),
    ],
  },
  'trap': {
    name: 'Trap',
    description: 'Trap night — 808s, hi-hats, and the drops the whole room rides.',
    items: [
      song('Future', 'Mask Off', 'Trap', '2010s'),
      lip('Migos', 'Walk It Talk It', 'Trap', '2010s', 'Three-man triplet flow'),
      song('Gucci Mane', 'Lemonade', 'Trap', '2000s'),
      song('21 Savage', 'A Lot', 'Trap', '2010s'),
      lip('Young Thug', 'Best Friend', 'Trap', '2010s', 'Nobody else can do this voice'),
      song('Travis Scott', 'SICKO MODE', 'Trap', '2010s'),
      song('Lil Baby', 'Drip Too Hard', 'Trap', '2010s'),
      lip('Future', 'Where Ya At', 'Trap', '2010s', 'Hook or nothing'),
      song('Playboi Carti', 'Magnolia', 'Trap', '2010s'),
      song('Lil Uzi Vert', 'XO Tour Llif3', 'Trap', '2010s'),
      lip('Gunna', 'Pushin P', 'Trap', '2020s', 'Slide with it'),
      song('Roddy Ricch', 'The Box', 'Trap', '2020s'),
      song('Moneybagg Yo', 'Said Sum', 'Trap', '2020s'),
      lip('Chief Keef', 'Love Sosa', 'Drill / Trap', '2010s', 'Full room shout'),
      song('Rae Sremmurd', 'Black Beatles', 'Trap', '2010s'),
      song('Metro Boomin', 'Creepin’', 'Trap / R&B', '2020s', 'mid'),
      lip('Waka Flocka Flame', 'No Hands', 'Trap', '2010s', 'No hands — literally'),
      song('Lil Durk', 'All My Life', 'Trap', '2020s'),
      song('Key Glock', 'Ambition For Cash', 'Trap', '2020s'),
      lip('2 Chainz', 'I’m Different', 'Trap', '2010s', 'Say it with your chest'),
      song('Young Dolph', 'Major', 'Trap', '2010s'),
      song('Jeezy', 'Soul Survivor', 'Trap', '2000s'),
      song('Future', 'Life Is Good', 'Trap', '2020s'),
      lip('Desiigner', 'Panda', 'Trap', '2010s', 'Nobody knows the words — try anyway'),
      song('Lil Baby', 'Freestyle', 'Trap', '2010s'),
      song('Sheck Wes', 'Mo Bamba', 'Trap', '2010s'),
    ],
  },
  'crunk': {
    name: 'Crunk',
    description: 'Crunk night — early-2000s Atlanta, and the loudest the floor gets all week.',
    items: [
      lip('Lil Jon & The East Side Boyz', 'Get Low', 'Crunk', '2000s', 'The whole room screams it'),
      song('Lil Jon', 'Turn Down for What', 'Crunk / EDM', '2010s'),
      song('Ying Yang Twins', 'Salt Shaker', 'Crunk', '2000s'),
      lip('Petey Pablo', 'Freek-A-Leek', 'Crunk', '2000s', 'Shirt over the head'),
      song('Trillville', 'Some Cut', 'Crunk', '2000s'),
      song('YoungBloodZ', 'Damn!', 'Crunk', '2000s'),
      lip('Ciara', 'Goodies', 'Crunk / R&B', '2000s', 'Crunk&B — smooth but loud'),
      song('David Banner', 'Like a Pimp', 'Crunk', '2000s'),
      song('Bone Crusher', 'Never Scared', 'Crunk', '2000s'),
      lip('Ying Yang Twins', 'Wait (The Whisper Song)', 'Crunk', '2000s', 'Whisper it, then don’t'),
      song('Pastor Troy', 'Vice Versa', 'Crunk', '2000s'),
      song('Lil Scrappy', 'Money in the Bank', 'Crunk', '2000s'),
      lip('Usher', 'Yeah!', 'Crunk / R&B', '2000s', 'Lil Jon ad-libs count'),
      song('T.I.', 'Bring Em Out', 'Crunk / Rap', '2000s'),
      song('Dem Franchize Boyz', 'Lean Wit It, Rock Wit It', 'Snap / Crunk', '2000s'),
      lip('E-40', 'Tell Me When to Go', 'Hyphy / Crunk', '2000s', 'Go dumb'),
      song('Unk', 'Walk It Out', 'Snap / Crunk', '2000s'),
      song('Crime Mob', 'Knuck If You Buck', 'Crunk', '2000s'),
      lip('Three 6 Mafia', 'Stay Fly', 'Crunk / Memphis', '2000s', 'Memphis drawl, all of it'),
      song('Lil Jon', 'Snap Yo Fingers', 'Crunk / Snap', '2000s'),
      song('Field Mob', 'Georgia', 'Crunk / Rap', '2000s'),
      song('Rasheeda', 'My Bubble Gum', 'Crunk', '2000s'),
      lip('Lil Jon & The East Side Boyz', 'What U Gon’ Do', 'Crunk', '2000s', 'Hands up, no exceptions'),
      song('Trick Daddy', 'Sugar (Gimme Some)', 'Crunk', '2000s'),
      song('Three 6 Mafia', 'Poppin’ My Collar', 'Crunk / Memphis', '2000s'),
      song('Bubba Sparxxx', 'Ms. New Booty', 'Crunk', '2000s'),
    ],
  },
  'kings-of-rnb': {
    name: 'Kings of R&B',
    description: 'The men of R&B — the voices grown folks came out to hear.',
    items: [
      lip('Usher', 'You Make Me Wanna...', 'R&B', '1990s', 'Footwork required'),
      song('Chris Brown', 'Take You Down', 'R&B', '2000s', 'mid'),
      song('Trey Songz', 'Say Aah', 'R&B', '2000s'),
      lip('Jodeci', 'Come & Talk to Me', 'R&B', '1990s', 'Full group harmony'),
      song('Ne-Yo', 'So Sick', 'R&B', '2000s', 'mid'),
      song('Miguel', 'Adorn', 'R&B', '2010s', 'mid'),
      lip('Boyz II Men', 'End of the Road', 'R&B', '1990s', 'Somebody take the low part'),
      song('Maxwell', 'Ascension (Don’t Ever Wonder)', 'Neo Soul', '1990s', 'mid'),
      song('Tank', 'When We', 'R&B', '2010s', 'mid'),
      lip('Keith Sweat', 'Nobody', 'R&B', '1990s', 'The whine is the whole point'),
      song('Bryson Tiller', 'Don’t', 'R&B', '2010s', 'mid'),
      song('Usher', 'Nice & Slow', 'R&B', '1990s', 'mid'),
      lip('D’Angelo', 'Untitled (How Does It Feel)', 'Neo Soul', '1990s', 'Brave choice — commit'),
      song('Ginuwine', 'Pony', 'R&B', '1990s'),
      song('Jagged Edge', 'Let’s Get Married', 'R&B', '2000s'),
      lip('Marvin Gaye', 'Let’s Get It On', 'Soul', '1970s', 'Grown folks only'),
      song('Joe', 'All the Things (Your Man Won’t Do)', 'R&B', '1990s', 'mid'),
      song('112', 'Peaches & Cream', 'R&B', '2000s'),
      lip('Luther Vandross', 'Never Too Much', 'Soul', '1980s', 'Smooth performer'),
      song('Brent Faiyaz', 'Trust', 'R&B', '2010s', 'mid'),
      song('Chris Brown', 'No Guidance', 'R&B', '2010s'),
      song('Dru Hill', 'In My Bed', 'R&B', '1990s'),
      lip('Al Green', 'Let’s Stay Together', 'Soul', '1970s', 'The one that never misses', 'mid'),
      song('Frank Ocean', 'Thinkin Bout You', 'R&B', '2010s', 'mid'),
      song('Silk', 'Freak Me', 'R&B', '1990s', 'mid'),
      song('Avant', 'Read Your Mind', 'R&B', '2000s', 'mid'),
    ],
  },
  'pop': {
    name: 'Pop',
    description: 'Pop night — the records absolutely everybody in the room already knows.',
    items: [
      lip('Whitney Houston', 'I Wanna Dance With Somebody', 'Pop', '1980s', 'Full crowd singalong'),
      song('Michael Jackson', 'Billie Jean', 'Pop', '1980s'),
      song('Dua Lipa', 'Levitating', 'Pop / Dance', '2020s'),
      lip('Britney Spears', '...Baby One More Time', 'Pop', '1990s', 'The schoolgirl stomp'),
      song('The Weeknd', 'Blinding Lights', 'Pop / Synth', '2010s'),
      song('Taylor Swift', 'Shake It Off', 'Pop', '2010s'),
      lip('Lady Gaga', 'Bad Romance', 'Pop / Dance', '2000s', 'The hands, then the whole thing'),
      song('Justin Timberlake', 'Can’t Stop the Feeling!', 'Pop', '2010s'),
      song('Harry Styles', 'As It Was', 'Pop', '2020s'),
      lip('Cher', 'Believe', 'Pop / Dance', '1990s', 'Auto-tune, the original'),
      song('Katy Perry', 'Firework', 'Pop', '2010s'),
      song('Bruno Mars', '24K Magic', 'Pop / Funk', '2010s'),
      lip('Backstreet Boys', 'I Want It That Way', 'Pop', '1990s', 'Somebody has to be Brian'),
      song('Miley Cyrus', 'Flowers', 'Pop', '2020s'),
      song('Olivia Rodrigo', 'good 4 u', 'Pop / Rock', '2020s'),
      lip('Madonna', 'Like a Prayer', 'Pop', '1980s', 'Choir energy'),
      song('Ed Sheeran', 'Shape of You', 'Pop', '2010s'),
      song('Sia', 'Cheap Thrills', 'Pop / Dance', '2010s'),
      lip('Prince', 'Kiss', 'Pop / Funk', '1980s', 'Falsetto or go home'),
      song('Beyoncé', 'Break My Soul', 'Pop / House', '2020s'),
      song('Maroon 5', 'Sugar', 'Pop', '2010s'),
      song('Carly Rae Jepsen', 'Call Me Maybe', 'Pop', '2010s'),
      lip('Queen', 'Bohemian Rhapsody', 'Rock / Pop', '1970s', 'All of it. Every part.'),
      song('Justin Bieber', 'Sorry', 'Pop / Dancehall', '2010s'),
      song('Lizzo', 'About Damn Time', 'Pop / Funk', '2020s'),
      song('Rihanna', 'Umbrella', 'Pop / R&B', '2000s'),
    ],
  },
  'movies': {
    name: 'Movies',
    description: 'Movie night — songs from the films, and the ones a whole generation knows by scene.',
    items: [
      lip('Whitney Houston', 'I Will Always Love You', 'Soundtrack / Soul', '1990s', 'The Bodyguard — go for the key change', 'mid'),
      song('Kendrick Lamar', 'All the Stars', 'Soundtrack / Rap', '2010s'),
      song('Bill Withers', 'Lovely Day', 'Soul', '1970s', 'mid'),
      lip('Eminem', 'Lose Yourself', 'Soundtrack / Rap', '2000s', '8 Mile — first verse, no breathing'),
      song('Survivor', 'Eye of the Tiger', 'Rock', '1980s'),
      song('Lady Gaga', 'Shallow', 'Soundtrack / Pop', '2010s', 'mid'),
      lip('Céline Dion', 'My Heart Will Go On', 'Soundtrack / Pop', '1990s', 'Titanic — arms out', 'mid'),
      song('Seal', 'Kiss From a Rose', 'Soundtrack / Pop', '1990s', 'mid'),
      song('Pharrell Williams', 'Happy', 'Soundtrack / Pop', '2010s'),
      lip('Elton John', 'Circle of Life', 'Soundtrack', '1990s', 'Lion King — the opening, obviously'),
      song('Coolio', 'Gangsta’s Paradise', 'Soundtrack / Rap', '1990s'),
      song('Ray Parker Jr.', 'Ghostbusters', 'Soundtrack / Funk', '1980s'),
      lip('Idina Menzel', 'Let It Go', 'Soundtrack', '2010s', 'Frozen — the kids will help'),
      song('Kenny Loggins', 'Danger Zone', 'Soundtrack / Rock', '1980s'),
      song('Will Smith', 'Men in Black', 'Soundtrack / Rap', '1990s'),
      lip('Will Smith', 'Wild Wild West', 'Soundtrack / Rap', '1990s', 'The whole intro'),
      song('Bee Gees', 'Stayin’ Alive', 'Soundtrack / Disco', '1970s'),
      song('Aerosmith', 'I Don’t Want to Miss a Thing', 'Soundtrack / Rock', '1990s', 'mid'),
      lip('Vanessa Williams', 'Colors of the Wind', 'Soundtrack', '1990s', 'Pocahontas — full commitment', 'mid'),
      song('R. Kelly', 'I Believe I Can Fly', 'Soundtrack / R&B', '1990s', 'mid'),
      song('Berlin', 'Take My Breath Away', 'Soundtrack / Pop', '1980s', 'mid'),
      song('Toni Braxton', 'Un-Break My Heart', 'Soundtrack / R&B', '1990s', 'mid'),
      lip('Prince', 'Purple Rain', 'Soundtrack / Rock', '1980s', 'The long one — earn it', 'mid'),
      song('Nelly', 'Hot in Herre', 'Rap', '2000s'),
      song('Tina Turner', 'We Don’t Need Another Hero', 'Soundtrack / Rock', '1980s', 'mid'),
      song('Bruce Springsteen', 'Streets of Philadelphia', 'Soundtrack / Rock', '1990s', 'mid'),
    ],
  },
};
// Attach the resolved YouTube id to every square that has one. Kept out of the
// deck definitions above so the song list stays readable and the resolver only
// ever rewrites one generated file — see src/deck-videos.mjs.
for (const deck of Object.values(BINGO_DECKS)) {
  for (const item of deck.items) {
    const vid = DECK_VIDEO_IDS[item.id];
    if (vid) item.videoId = vid;
  }
}

export const DEFAULT_DECK_ID = 'after-spot-starter';
export const deckList = () => Object.entries(BINGO_DECKS).map(([id, d]) => ({ id, name: d.name, description: d.description, count: d.items.length }));
export const deckById = (id) => BINGO_DECKS[id] || BINGO_DECKS[DEFAULT_DECK_ID];
